In [107]:
import tensorflow as tf
import numpy as np
import datetime, os
from keras.utils.np_utils import to_categorical
import matplotlib.pyplot as plt

In [108]:
import pandas as pd

In [109]:
data = pd.read_csv('/content/classification.csv')

In [114]:
x_train = data['valeurs']
y_train = data['label']
x_val = data['valeurs_val']
y_val = data['label_val']
x_val  = x_val[0:70]
y_val = y_val[0:70]

In [115]:
for i in range(0,len(y_val)):
  if y_val[i] == 'R1':
    y_val[i] = 1
  if y_val[i] == 'R2':
    y_val[i] = 2
  if y_val[i] == 'R3':
    y_val[i] = 3
  if y_val[i] == 'R4':
    y_val[i] = 4

for i in range(0,len(y_train)):
  if y_train[i] == 'R1':
    y_train[i] = 1
  if y_train[i] == 'R2':
    y_train[i] = 2
  if y_train[i] == 'R3':
    y_train[i] = 3
  if y_train[i] == 'R4':
    y_train[i] = 4

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_laun

In [116]:
print(x_train.shape)

(818,)


In [117]:
x_train = np.asarray(x_train)
x_val = np.asarray(x_val)
y_val = np.asarray(y_val)
y_train = np.asarray(y_train)
y_train = to_categorical(y_train)
y_val = to_categorical(y_val)
print(x_train.shape)
print(y_train.shape)
print(y_val)

(818,)
(818, 5)
[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0

In [118]:
model = tf.keras.Sequential()

In [123]:
METRICS = ['accuracy']

model.add(tf.keras.layers.Dense(64, activation='relu',input_dim=1))
model.add(tf.keras.layers.Dense(5, activation = 'softmax'))

print(model.summary)

model.compile(loss='categorical_crossentropy', optimizer = 'SGD', metrics = ['accuracy'])
model.fit(x_train,y_train,epochs=20,validation_data = (x_val,y_val))

<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x7fd80c7b5910>>
Epoch 1/20
26/26 [==============================] - 1s 10ms/step - loss: 1.5799 - accuracy: 0.2910 - val_loss: 1.5845 - val_accuracy: 0.2857
Epoch 2/20
26/26 [==============================] - 0s 3ms/step - loss: 1.5396 - accuracy: 0.3411 - val_loss: 1.5600 - val_accuracy: 0.2857
Epoch 3/20
26/26 [==============================] - 0s 3ms/step - loss: 1.5099 - accuracy: 0.3704 - val_loss: 1.5413 - val_accuracy: 0.2857
Epoch 4/20
26/26 [==============================] - 0s 3ms/step - loss: 1.4868 - accuracy: 0.3704 - val_loss: 1.5270 - val_accuracy: 0.2857
Epoch 5/20
26/26 [==============================] - 0s 3ms/step - loss: 1.4680 - accuracy: 0.3704 - val_loss: 1.5160 - val_accuracy: 0.2857
Epoch 6/20
26/26 [==============================] - 0s 3ms/step - loss: 1.4528 - accuracy: 0.3704 - val_loss: 1.5070 - val_accuracy: 0.2857
Epoch 7/20
26/26 [==============================] - 0s 3ms/step -

In [122]:
model.predict([30])

array([[0.04060513, 0.15574194, 0.3630363 , 0.15967314, 0.28094354]],
      dtype=float32)